version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4-apache
    container_name: php-container
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    networks: 
      - default
