---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: php-container
        image: dheerendrabhandari/php-project
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-php-service
spec:
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
