apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: 
        image: dheerendrabhandari/php-project
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: my-php-service
spec:
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
